[customizations.installer.kickstart]
contents = """
%post
mkdir -p /mnt/sysroot/usr/share/
cp -a /run/initramfs/pixmaps /mnt/sysroot/usr/share/
echo "Switching to image: ${BOOTC_IMAGE}"
chroot /mnt/sysroot bootc switch --mutate-in-place --transport registry ${BOOTC_IMAGE}
%end
"""

[customizations.installer.modules]
enable = [
    "org.fedoraproject.Anaconda.Modules.Storage",
    "org.fedoraproject.Anaconda.Modules.Network",
    "org.fedoraproject.Anaconda.Modules.Users",
]
disable = [
    "org.fedoraproject.Anaconda.Modules.Security",
    "org.fedoraproject.Anaconda.Modules.Services",
    "org.fedoraproject.Anaconda.Modules.Subscription",
    "org.fedoraproject.Anaconda.Modules.Timezone",
]
