name: Build Image

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/BuildIso*.yml"
      - "Build/iso.toml"
      - "**/README.md"
  schedule:
    - cron: "5 5 * * 1,5"
  workflow_dispatch:

env:
  BASE_VERSION: "v0.3"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.set_tag.outputs.release_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all git tags
        run: git fetch --tags

      - name: Determine next release tag (semver-style)
        id: set_tag
        run: |
          latest=$(git tag | grep "^${BASE_VERSION}\." | sed "s/^${BASE_VERSION}\.//" | sort -V | tail -n 1)
          if [ -z "$latest" ]; then
            next=0
          else
            next=$((latest + 1))
          fi
          TAG="${BASE_VERSION}.${next}"
          echo "release_tag=$TAG" >> $GITHUB_OUTPUT
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV

      - name: Create GitHub release (if not exists)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh release view "$RELEASE_TAG" &>/dev/null; then
            gh release create "$RELEASE_TAG" --title "$RELEASE_TAG" --notes "Atomized Container Images"
          fi

      - name: Trigger image build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 12_Image_Build.yml
          inputs: |
            {
              "release_tag": "${{ steps.set_tag.outputs.release_tag }}"
            }
