name: Image Workflow

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "55 5 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and push ${{ matrix.variant.name }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        variant:
          - name: bazzite
            base_image: ghcr.io/ublue-os/bazzite:stable
          - name: bazzite-nvidia
            base_image: ghcr.io/ublue-os/bazzite-nvidia:stable

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      BASE_IMAGE: ${{ matrix.variant.base_image }}
      IMAGE_TAG: ${{ matrix.variant.name }}
      IMAGE_DESC: "Personalized Atomic OS Image"
      IMAGE_KEYWORDS: "bootc,ublue,universal-blue"
      IMAGE_LOGO_URL: "https://avatars.githubusercontent.com/u/103059356?s=200&v=4"
      IMAGE_NAME: "${{ github.event.repository.name }}-${{ matrix.variant.name }}"
      IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
      DEFAULT_TAG: "latest"

    steps:
      - name: Prepare environment
        run: |
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Mount BTRFS for podman storage
        uses: ublue-os/container-storage-action@main

      - name: Get current date
        id: date
        run: echo "date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

      - name: Image Metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          tags: |
            type=raw,value=${{ env.DEFAULT_TAG }}
            type=raw,value=${{ env.DEFAULT_TAG }}-${{ matrix.variant.name }}.${{ steps.date.outputs.date }}
            type=raw,value=${{ matrix.variant.name }}.${{ steps.date.outputs.date }}
            type=sha,enable=${{ github.event_name == 'pull_request' }}
            type=ref,event=pr
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/blob/main/Containerfile
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.version=${{ env.DEFAULT_TAG }}.${{ steps.date.outputs.date }}
            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
            io.artifacthub.package.logo-url=${{ env.IMAGE_LOGO_URL }}
            io.artifacthub.package.keywords=${{ env.IMAGE_KEYWORDS }}

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          oci: false
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.metadata.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.9.1
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

      - name: Sign container image
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          IMAGE_FULL="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"
          for tag in ${{ steps.metadata.outputs.tags }}; do
            cosign sign -y --key env://COSIGN_PRIVATE_KEY "$IMAGE_FULL:$tag"
          done
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
